apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.ObjectMeta.Name}}
  namespace: {{.ObjectMeta.Namespace}}
  labels:
    app: {{.ObjectMeta.Name}}
spec:
  replicas: {{.Spec.EmbeddedResource.Replicas}}
  type: {{.Spec.EmbeddedResource.AccessScope}}
  selector:
    matchLabels:
      app: {{.ObjectMeta.Name}}
  template:
    metadata:
      labels:
        app: {{.ObjectMeta.Name}}
    spec:
      #hostAliases临时解决方案，后续删除
      hostAliases:
        - ip: "10.43.73.65"
          hostnames:
            - "registrycenter-master"
      containers:
        - name: {{.ObjectMeta.Name}}
          image: {{.Spec.Image.Name}}
          ports:
            - containerPort: 8080
          env:
            {{range .Spec.Env}}
            - name: {{.Name}}
              value: {{.Value}}
            {{end}}