apiVersion: hanweb.jpaas.deploy/v1beta1
kind: JPaasApp
metadata:
  labels:
    app.kubernetes.io/name: jpaas
    app.kubernetes.io/instance: {{(index .Spec.AppRefs 0).Name}}
    app.kubernetes.io/part-of: kubedev
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubedev
  name: {{(index .Spec.AppRefs 0).Name}}
  namespace: {{.ObjectMeta.Namespace}}
spec:
  image:
    name: {{printf "%s%s:%s" .Spec.ImageUrl (index .Spec.AppRefs 0).Name (index .Spec.AppRefs 0).Version}}
  embeddedResource:
    replicas: 1
    accessScope: {{(index .Spec.AppRefs 0).AccessScope}}
    ports:
      port: 8080
      Scope: ClusterIP
      Name: Health
  env:
  {{range .Spec.CommonEnv}}
  - name: {{.Name}}
    value: {{.Value}}
  {{end}}
  version: {{(index .Spec.AppRefs 0).Version}}
  health: false
  type: {{(index .Spec.AppRefs 0).Type}}
  resources:
    limits:
      cpu: 100m
      memory: 100Mi