apiVersion: v1
kind: Service
metadata:
  name: {{.ObjectMeta.Name}}
  namespace: {{.ObjectMeta.Namespace}}
spec:
  type: {{.Spec.EmbeddedResource.AccessScope}}
  selector:
    app: {{.ObjectMeta.Name}}
  ports:
    - name: health
      port: 8080
      protocol: TCP
      targetPort: 80
status: {}